apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jhsong-nginx-replicaset
  namespace: jhsong-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      web: nginx
  template:
    metadata:
      name: jhsong-nginx
      labels:
        web: nginx
    spec:   
      containers:
      - name: jhsong-nginx
        image: nginx
        livenessProbe:
          httpGet:
            path: /
            port: 8080

