apiVersion: v1
kind: Pod
metadata:
  name: jhsong-flask
  namespace: jhsong-namespace
  labels:
    app: flask
spec:
  containers:
    - name: gunicorn
      image: jihyungsong/gunicorn:fargate
      ports: 
      - containerPort: 5000
        protocol: TCP
    - name: nginx
      image: jihyungsong/nginx:fargate
      ports:
      - containerPort: 80 
        protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
