apiVersion: v1
kind: Pod
metadata:
  name: jhsong-nginx
  namespace: jhsong-namespace
  labels:
    web: nginx
spec:
  containers:
    - name: jhsong-nginx
      image: nginx
      ports: 
        - containerPort: 80
          protocol: TCP
