apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: bluese05
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30031
    selector:
        app: nginx
