apiVersion: v1
kind: Service
metadata:
    name: flask-service
    namespace: jhsong-namespace
    annotations:
      service.beta.kuberntes.io/aws-load-balancer-type: nlb-ip
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
    selector:
        app: flask
