apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: bluese05
spec:
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: bluese05-nginx

