apiVersion: v1
kind: Pod
metadata:
  name: bluese05-nginx
  namespace: bluese05
  labels:
    web: nginx
spec:
  containers:
    - name: bluese05-nginx
      image: nginx
      ports: 
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
